### ISSUE TITLE
Example for matching statements?

### ISSUE THREAD

**Issue by landaire** [dtolnay/tt-call#13]
I wrote the following terrible and fragile macro today that, in the process of trying to clean up, led me to this crate. The macro can be seen here: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=168417a6a680b4414400a92b3c7ff36a

The gist is that given some input tokens, I'd like to wrap each statement that does not result in the creation of a new variable with an `if`. e.g.:

```rust
loose_fixup! {
    self.length = self.dynamic_vector.serialized_size();
    if self.type == SomeType {
        self.flag = true;
    }
}
```

Expands to:

```rust
if random() {
    self.length = self.dynamic_vector.serialized_size();
}
if self.type == SomeType {
    if random() {
        self.flag = true;
    }
}
```

This should be *every* statement passed to the macro -- even those contained within `match` arms and `if` conditions. I was thinking that this crate may help me clean things up, but I'm not entirely certain after attempting to get a replacement example working. Here was what I tried:

```rust
use tt_call::{tt_call, tt_replace, tt_return};

macro_rules! is_statement {
    {
        $caller:tt
        input = [{ $statement:stmt; }]
    } => {
        tt_return! {
            $caller
            is = [{ true }]
        }
    };

    {
        $caller:tt
        input = [{ $other:tt }]
    } => {
        tt_return! {
            $caller
            is = [{ false }]
        }
    };
}

macro_rules! loose_fixup {
    { $($rest:tt)+ } => {
        tt_call! {
            macro = [{ tt_replace }]
            condition = [{ is_statement }]
            replace_with = [{ if true {
                println!("bar");
            } }]
            input = [{ $($rest)+ } ]
        }
    };
}

fn main() {
    loose_fixup! {
        println!("foo");
    };
}
```

The example for `tt_replace!` is a bit more simple -- just matching on `self` or a single `tt`, so I wasn't too surprised when it failed:

```λ cargo expand
    Checking tt-test v0.1.0 (S:\development\tt-test)
error: expected expression, found `}`
  --> src\main.rs:39:5
   |
39 | /     loose_fixup! {
40 | |         println!("foo");
41 | |     };
   | |      ^
   | |      |
   | |______expected expression
   |        in this macro invocation
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
error: expected a statement
  --> src\main.rs:39:5
   |
39 | /     loose_fixup! {
40 | |         println!("foo");
41 | |     };
   | |______^ in this macro invocation
   |
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
error: aborting due to 2 previous errors
error: Could not compile `tt-test`.
To learn more, run the command again with --verbose.```

Is this crate not appropriate for this type of situation? Are there any other utility crates which may be useful to clean this up?

**Comment by dtolnay** [comment]
I am not going to be able to provide a lot of help on this due to time, but you are on the right track. The existing tt_replace is defined as acting on individual tokens though. You would want to put together something similar that operates on statements rather than tokens.

**Comment by landaire** [comment]
That's totally fine, I just wanted to see if this was the appropriate crate to use as a framework or if I was misusing it. Thanks! I'll update this post if I derive a good solution.
